import type { Metadata } from "next";
import React from "react";
import MainLayout from "@/app/(root)/tutorial/MainLayout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface Props {
    children: React.ReactNode;
}
const TutorialLayout: React.FC<Props> = props => {
    const { children } = props;
    return (
        <main>
            <MainLayout>{children}</MainLayout>
        </main>
    );
};
export default TutorialLayout;
